#ifndef CUBESIMULATIONLIBRARY_GLOBAL_H
#define CUBESIMULATIONLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUBESIMULATIONLIBRARY_LIBRARY)
#  define CUBESIMULATIONLIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CUBESIMULATIONLIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CUBESIMULATIONLIBRARY_GLOBAL_H
